description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: 25 Nov 2021
fullnameofperson: Amanda Miotto
selfIdentification: eResearch Analyst and lover of Science and IT
colour1: "#006D77"  # sidebar background 
colour2: "#83C5BE"  # colour of name and desc
colour3: "#83C5BE"  # colour of Menu links
colour4: "#EDF6F9" # trying to be background colour - still experimenting 
colour5: "#E29578" # menu link colour when hover
imgfilename: ProfilePhoto.JPG  # name of your profile pic file, stored in assets
